### ISSUE TITLE
大佬你好，编译不过

### ISSUE THREAD

**Issue by gaoguanqi** [Ysj001/DoKitPluginCompat#3]
![image](https://github.com/Ysj001/DoKitPluginCompat/assets/12546980/b4730c7c-eb95-477f-9092-554897f3be05)

**Comment by Ysj001** [comment]
构建脚本写错了，检查你的 app 模块构建脚本是 build.gradle 还是 build.gradle.kts。README 中有分别两种脚本的写法可以去参考。
