### ISSUE TITLE
编译时 提示 如下appHexaDebugBCUTransformTask exception

### ISSUE THREAD

**Issue by showwiki** [Ysj001/DoKitPluginCompat#4]
Execution failed for task ':app:appHexaDebugBCUTransformTask'.
> No signature of method: build_6en9k89pnhg6wm0tj158bbpr$_run_closure3$_closure23.doCall() is applicable for argument types: (com.ysj.lib.bytecodeutil.plugin.Config, com.android.build.api.variant.impl.ApplicationVariantImpl_Decorated) values: [com.ysj.lib.bytecodeutil.plugin.Config@7d91ce16, com.android.build.api.variant.impl.ApplicationVariantImpl_Decorated@6e894132]
  Possible solutions: doCall(java.lang.Object), findAll(), findAll()

**Comment by Ysj001** [comment]
语法错误，readme中提供了groovy和kts版本的例子，先点进去看一遍
