### ISSUE TITLE
未引入插件或插件未开启

### ISSUE THREAD

**Issue by zsh1111111111111** [Ysj001/DoKitPluginCompat#6]
根据文档替换成dokit-compat之后点击网络提示未引入插件或插件未开启

**Comment by Ysj001** [comment]
无法根据你的描述了解原因，请确保根据文档正确配置，若还不行提供你的配置

**Comment by zsh1111111111111** [comment]
按照文档配置 下来报错/android/app/build/intermediates/classes/aitalkDebug/aitalkDebugBCUAppendTask/LICENSE.txt: The destination file already exists.
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/1ea58026-9203-4759-a54f-dcbf07ba175e">

**Comment by Ysj001** [comment]
尝试 clean 后还是不行的话，可以提供下这个冲突的 LICENSE.txt 位置截图

**Comment by zsh1111111111111** [comment]
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/f6e88ba3-1e01-4b3d-8c4b-450ac6a6615e">
这个吗

**Comment by zsh1111111111111** [comment]
clean没用 clean过好几遍了

**Comment by Ysj001** [comment]
好的，麻烦截图看看这个文件位置，为啥会参与编译了

**Comment by zsh1111111111111** [comment]
<img width="462" alt="image" src="https://github.com/user-attachments/assets/82d8762b-8747-48da-86c3-0801de53fd59">
<img width="396" alt="image" src="https://github.com/user-attachments/assets/0b97cc1d-86c8-4f8c-a20f-bb4b874ee2c1">
怎么看参与编译啊  不是很懂安卓

**Comment by Ysj001** [comment]
这是编译的中间输出目录，你可以直接吧 app/build 目录删除后尝试重新编译。另外麻烦提供这个 LICENSE.txt 文件的原始位置截图

**Comment by zsh1111111111111** [comment]
<img width="994" alt="image" src="https://github.com/user-attachments/assets/38f695d6-3f62-4849-9c4b-0cc40eceec7b">
是这个吗 我没找到原始位置

**Comment by Ysj001** [comment]
不是这个，这个是报错代码的堆栈信息，我想了解原因，目前推测你的项目配置的有点问题

**Comment by zsh1111111111111** [comment]
是我接入的代码有问题吗？
![image](https://github.com/user-attachments/assets/36351359-56e6-4fa3-ad13-ce0dbfa2496f)
![image](https://github.com/user-attachments/assets/2d4cb051-c068-4632-ad4d-a97275441ad3)
![image](https://github.com/user-attachments/assets/b1abf7ee-a0cd-4d2d-a0ec-eac24a98b614)
![image](https://github.com/user-attachments/assets/2b0d47d8-6d78-487d-85f6-3e49eb0ac1d3)
![image](https://github.com/user-attachments/assets/e4cdc3c7-e4c3-4098-80c7-5ce23ace1126)
就改了这些代码

**Comment by Ysj001** [comment]
你那边 clean 后 app/build 目录还存在吗，手动删除 app/build 目录后编译还有问题说明有不止一个 LICENSE.txt 在根目录中参与编译了，需要找到这个文件将其排除编译或删除

**Comment by Ysj001** [comment]
不会配置过滤的话 filterNot 直接返回 false，不进行过滤，走全量编译，调整完配置后任意改动一行代码触发缓存失效

**Comment by zsh1111111111111** [comment]
我手动删了build文件 然后 filterNot 返回 false 但是还是失败了
<img width="560" alt="image" src="https://github.com/user-attachments/assets/28d0d52c-cd09-4233-96d6-23e5b3e72cad">

**Comment by zsh1111111111111** [comment]
怎么找这个原始文件啊 我搜LICENSE 搜不到

**Comment by Ysj001** [comment]
可以看下你的报错信息有么有变，有任意改动一下代码吗，否则走缓存，配置是无效的

**Comment by zsh1111111111111** [comment]
报错信息没变，然后我刚刚改了代码，把这里开关变成false了
![image](https://github.com/user-attachments/assets/f8061997-ff91-4019-9415-28bc82939d27)

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/631e0978-4bd5-43f4-a75a-0183b1dd5801">

**Comment by Ysj001** [comment]
不是改这里，这个构建配置，你改一下源码，随便加点换行什么的

**Comment by Ysj001** [comment]
![图片](https://github.com/user-attachments/assets/3e4f0d1c-f1f7-4b4b-b626-af41c860b728)
搜索用 android stuio 如图

**Comment by zsh1111111111111** [comment]
![image](https://github.com/user-attachments/assets/f663b44e-0695-4667-bd7c-36fbb9cf64c7)

**Comment by zsh1111111111111** [comment]
<img width="585" alt="image" src="https://github.com/user-attachments/assets/d236ff15-7f31-4a52-acd0-9bab8e93c3af">
这两个就是之前报错说已经存在的两个

**Comment by Ysj001** [comment]
唉，好头疼，这个 build 目录下的都是构建中间产物，你删了不要管，你先改下源码触发先缓存更新重编译吧

**Comment by zsh1111111111111** [comment]
我没找到源码啊 我不是直接down的marvel上的吗

**Comment by Ysj001** [comment]
![图片](https://github.com/user-attachments/assets/8ed94eb3-59b0-493b-bc08-794345ff46a0)
这个删掉

**Comment by Ysj001** [comment]
![图片](https://github.com/user-attachments/assets/58e316bd-a149-472b-8d22-1412b1261494)
这个就是你的源码，你加俩换行，在重新编译

**Comment by zsh1111111111111** [comment]
![image](https://github.com/user-attachments/assets/c804bee3-dbd7-4418-9501-d5564cfafa53)
改了源码 报错信息也没变

**Comment by Ysj001** [comment]
buc 依赖更新到 2.1.2 试试
com.github.Ysj001:BytecodeUtil:2.1.2

**Comment by zsh1111111111111** [comment]
改成2.1.2还是不行还是一样的报错
<img width="1231" alt="image" src="https://github.com/user-attachments/assets/bfb0ef1c-091b-4856-86a3-94d899cd4fa0">
<img width="775" alt="image" src="https://github.com/user-attachments/assets/05c7e3af-ae13-4d6e-8f6e-5630c5bfe62d">

**Comment by Ysj001** [comment]
这个文件冲突问题建议你这边找熟悉Android的同学排查一下项目具体冲突位置去解决，造成这个冲突的原因是不同模块或依赖有同名文件(LICENSE)都参与了编译导致的，并不属于本项目问题。
