### ISSUE TITLE
可以兼容Gradle-Repo插件使用么

### ISSUE THREAD

**Issue by ckrgithub** [Ysj001/DoKitPluginCompat#7]
支持AGP 8+以上的，Gradle-Repo插件使用。项目：https://github.com/EastWoodYang/Gradle-Repo

**Comment by Ysj001** [comment]
本项目的插件是对 AGP 中一些功能的封装，理论上不影响其它插件使用。
你在混合使用 Gradle-Repo 中遇到问题了吗，可以提供更详细的描述。

**Comment by ckrgithub** [comment]
> 本项目的插件是对 AGP 中一些功能的封装，理论上不影响其它插件使用。 你在混合使用 Gradle-Repo 中遇到问题了吗，可以提供更详细的描述。

@Ysj001 由于 Gradle-Repo 插件目前不兼容 AGP8+，所以没法使用，导致编译不通过

**Comment by Ysj001** [comment]
BytecodeUtil 最低可以支持 AGP 7.4.x，可以降低 AGP 版本再尝试，另外本项目只是为了兼容 DoKit 在 AGP 8+ 上无法使用的问题，如果你想使用小于 8 的 AGP 版本建议直接使用 DoKit 官方版本

**Comment by ckrgithub** [comment]
> BytecodeUtil 最低可以支持 AGP 7.4.x，可以降低 AGP 版本再尝试，另外本项目只是为了兼容 DoKit 在 AGP 8+ 上无法使用的问题，如果你想使用小于 8 的 AGP 版本建议直接使用 DoKit 官方版本
@Ysj001 我的意思是项目只想使用 Gradle-Repo 插件，不使用 DoKit插件。能不能支做一个持AGP 8+以上的Gradle-Repo插件，谢谢

**Comment by Ysj001** [comment]
> > BytecodeUtil 最低可以支持 AGP 7.4.x，可以降低 AGP 版本再尝试，另外本项目只是为了兼容 DoKit 在 AGP 8+ 上无法使用的问题，如果你想使用小于 8 的 AGP 版本建议直接使用 DoKit 官方版本
> > @Ysj001 我的意思是项目只想使用 Gradle-Repo 插件，不使用 DoKit插件。能不能支做一个持AGP 8+以上的Gradle-Repo插件，谢谢

抱歉，我没有使用过 Gradle-Repo，你应该去找 Gradle-Repo 的作者。本项目兼容 DoKit 的目的是为了解决高版本 AGP Transform 接口变更导致无法使用的问题。
