### ISSUE TITLE
怎么在打包的时候关掉BCU，只在debug的时候用Dokit

### ISSUE THREAD

**Issue by wsdydeni** [Ysj001/DoKitPluginCompat#8]

**Comment by Ysj001** [comment]
> _No description provided._

BCU 目前没有提供关闭功能，移除插件即相当于关闭。
你可以尝试在构建脚本中动态添加插件来做到类似效果。
如果想简单点可以在 BCU 的 filterNot 中根据 variant 判断，如果非 debug 直接返回 true，此时所有 class 都不会走 transform。

**Comment by Ysj001** [comment]
可关注后续 BCU 版本，可能会优化该问题。比如在 config 中如果未配置 modifier 时，则直接跳过相关逻辑。
